### ISSUE TITLE
Routes

### ISSUE THREAD

**Issue by PLUCS2** [JGYaniv/ArtAsk#3]
Backend: 
- [x] Change `update` to patch or put 
- [x] You may want to have reviews nested so that you have reference for what task they correspond to

Frontend: 
- [x] Can we fix this formatting?

**Comment by JGYaniv** [comment]
I *think* the formatting is fixed, sorry about the messiness before, this section is a bit in flux!

I was planning for the reviews to only be accessible from the task show page. That's why I only have `get /api/tasks/:taskId/reviews` nested. Is this correctly represented by my docs? What else would you recommend I nest?

**Comment by JGYaniv** [comment]
> You may want to have reviews nested so that you have reference for what task they correspond to

I don't think we discussed this point. Please see my comment above!
